### ISSUE TITLE
ERROR:Could not stream data to Openlayer DataResource.stream() got an unexpected keyword argument 'id'

### ISSUE THREAD

**Issue by reterVision** [openlayer-ai/openlayer-python#281]
Followed the Python example code to trace Azure OpenAI but getting this error, can anyone help?

**Comment by reterVision** [comment]
Posted a fix: https://github.com/openlayer-ai/openlayer-python/pull/282

**Comment by gustavocidornelas** [comment]
Thanks for the fix! I've replied to your PR.

Version 0.2.0-alpha.14 has it.
